Repository engeir/simple-recipes-cookbook, pull requests merged in 2022-05, with the labels that each got.

#9 Pizza dough
  src/hovedretter/pizza-deig.md
Labels: recipe

#10 Update pizza-deig.md
  src/hovedretter/pizza-deig.md
Labels: typo

#12 Contributing guide
  src/blog/2021-12-24-again.md
  src/blog/2022-5-24-hvordan-bidra.md
  src/index.md
Labels: documentation, enhancement

#15 Create pizzatopping-paere-skinke.md
  src/hovedretter/pizzatopping-paere-skinke.md
Labels: recipe
